//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBA_Bewerbe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model_FeuerwehrbewerbContainer : DbContext
    {
        public Model_FeuerwehrbewerbContainer()
            : base("name=Model_FeuerwehrbewerbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tBewerb> tBewerbSet { get; set; }
        public DbSet<tMannschaft> tMannschaftSet { get; set; }
        public DbSet<tTeilnehmendeMannschaft> tTeilnehmendeMannschaftSet { get; set; }
        public DbSet<tBahn> tBahnSet { get; set; }
        public DbSet<tTyp> tTypSet { get; set; }
        public DbSet<tTeilnehmer> tTeilnehmerSet { get; set; }
        public DbSet<tLauf> tLaufSet { get; set; }
    }
}
