//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBA_Bewerbe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model_FeuerwehrbewerbContainer : DbContext
    {
        public Model_FeuerwehrbewerbContainer()
            : base("name=Model_FeuerwehrbewerbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tBewerb> tBewerbSet { get; set; }
        public DbSet<tMannschaft> tMannschaftSet { get; set; }
        public DbSet<tTeilnehmendeMannschaft> tTeilnehmendeMannschaftSet { get; set; }
        public DbSet<tBahn> tBahnSet { get; set; }
        public DbSet<tTyp> tTypSet { get; set; }
        public DbSet<tTeilnehmer> tTeilnehmerSet { get; set; }
        public DbSet<tLauf> tLaufSet { get; set; }
    }
}
