//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBA_Bewerbe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBewerb
    {
        public tBewerb()
        {
            this.ZOT_Bewerb_Mannschaft = new ObservableListSource<tTeilnehmendeMannschaft>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual ObservableListSource<tTeilnehmendeMannschaft> ZOT_Bewerb_Mannschaft { get; set; }
    }
}
