//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBA_Bewerbe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBewerb
    {
        public tBewerb()
        {
            this.ZOT_Bewerb_Mannschaft = new ObservableListSource<tTeilnehmendeMannschaft>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual ObservableListSource<tTeilnehmendeMannschaft> ZOT_Bewerb_Mannschaft { get; set; }
    }
}
