//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBA_Bewerbe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLauf
    {
        public int Id { get; set; }
        public System.DateTime Nettozeit { get; set; }
        public System.DateTime Strafsekunden { get; set; }
    
        public virtual tBahn tBahn { get; set; }
        public virtual tTyp tTyp { get; set; }
        public virtual tTeilnehmendeMannschaft ZOT_Bewerb_Mannschaft { get; set; }
    }
}
