//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBA_Bewerbe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTeilnehmendeMannschaft
    {
        public tTeilnehmendeMannschaft()
        {
            this.tLauf = new ObservableListSource<tLauf>();
        }
    
        public int Id { get; set; }
        public string Startnummer { get; set; }
        public int Platzierung { get; set; }
    
        public virtual tBewerb tBewerb { get; set; }
        public virtual tMannschaft tMannschaft { get; set; }
        public virtual ObservableListSource<tLauf> tLauf { get; set; }
    }
}
