//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBA_Bewerbe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTeilnehmendeMannschaft
    {
        public tTeilnehmendeMannschaft()
        {
            this.tLauf = new ObservableListSource<tLauf>();
        }
    
        public int Id { get; set; }
        public string Startnummer { get; set; }
        public int Platzierung { get; set; }
        public int BewerbID { get; set; }
        public int MannschaftID { get; set; }
    
        public virtual tBewerb tBewerb { get; set; }
        public virtual tMannschaft tMannschaft { get; set; }
        public virtual ObservableListSource<tLauf> tLauf { get; set; }
    }
}
