//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBA_Bewerbe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTyp
    {
        public tTyp()
        {
            this.tLauf = new ObservableListSource<tLauf>();
        }
    
        public string Kuerzel { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual ObservableListSource<tLauf> tLauf { get; set; }
    }
}
