//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBA_Bewerbe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTyp
    {
        public tTyp()
        {
            this.tLauf = new ObservableListSource<tLauf>();
        }
    
        public string Kuerzel { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual ObservableListSource<tLauf> tLauf { get; set; }
    }
}
