//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF_Bewerbe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model_FeuerwehrbewerbContainer : DbContext
    {
        public Model_FeuerwehrbewerbContainer()
            : base("name=Model_FeuerwehrbewerbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tBewerb> tBewerbSet { get; set; }
        public virtual DbSet<tMannschaft> tMannschaftSet { get; set; }
        public virtual DbSet<tTeilnehmendeMannschaft> tTeilnehmendeMannschaftSet { get; set; }
        public virtual DbSet<tBahn> tBahnSet { get; set; }
        public virtual DbSet<tTyp> tTypSet { get; set; }
        public virtual DbSet<tTeilnehmer> tTeilnehmerSet { get; set; }
        public virtual DbSet<tLauf> tLaufSet { get; set; }
    }
}
