//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF_Bewerbe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLauf
    {
        public int Id { get; set; }
        public System.DateTime Nettozeit { get; set; }
        public System.DateTime Strafsekunden { get; set; }
    
        public virtual tBahn tBahn { get; set; }
        public virtual tTyp tTyp { get; set; }
        public virtual tTeilnehmendeMannschaft ZOT_Bewerb_Mannschaft { get; set; }
    }
}
