//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF_Bewerbe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTeilnehmendeMannschaft
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTeilnehmendeMannschaft()
        {
            this.tLauf = new HashSet<tLauf>();
        }
    
        public int Id { get; set; }
        public string Startnummer { get; set; }
        public int Platzierung { get; set; }
    
        public virtual tBewerb tBewerb { get; set; }
        public virtual tMannschaft tMannschaft { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tLauf> tLauf { get; set; }
    }
}
